print("<!doctype html>")
print("<html lang=\"en\">")
print("     <head>")
print("         <meta charset=\"utf-8\">")
print("         <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">")
print("         <title>Hello world!</title>")
print("         <style>")
print("             html {")
print("                 font-family: Verdana, Geneva, Tahoma, sans-serif;")
print("                 text-align: center;")
print("             }")
print("         </style>")
print("     </head>")
print("     <body>")
print("         <h1>Hello world!</h1>")
print("         <p>Hello world!</p>")
print("     </body>")
print("</html>")